### PR TITLE
YouTube TV uses blur event as well. Resolves #4

### LINKED ISSUE #4: Fix YouTube TV
The [YouTube TV ](youtube.com/tv) site has recently implemented a similar feature where switching tabs pauses the video. I have tried several extensions that promise to block the Page Awareness API, but with no luck, so I assume they use additional measures to do this. 

Perhaps you have any ideas on how to fix it.

### PR DESCRIPTION
**Pull request by Lusito**
Not 100% sure this is side effects free, but other inputs still receive the blur event, so I guess it should be fine.

### CODE REVIEW

**Comment by timdream** [comment]
@buttercookie42 Would you like to review this? This may be a better solution than #11.

**Comment by buttercookie42** [comment]
@Lusito: As I cannot test this, can you confirm that this is still required and that your fix is still working?

**Comment by Madis0** [comment]
> As I cannot test this

I'm curious about why couldn't you test this, though. This is about the [TV interface for YouTube](https://www.youtube.com/tv), not the [region-locked, paid streaming service](https://tv.youtube.com/welcome/).

**Comment by buttercookie42** [comment]
I had googled "Youtube TV" and only found the latter, not the former. (Also didn't look closely enough at your issue). Sorry for the confusion and thanks for clearing this up.

**Pull request closed without merging**
