### PR TITLE
Add Twitter to URL matches

### PR DESCRIPTION
**Pull request by nils-werner**
Twitter also mutes video when the tab is switched.

### CODE REVIEW

**Comment by timdream** [comment]
@buttercookie42 Would you like to review this?

**Comment by buttercookie42** [comment]
@nils-werner: Can you confirm that this is still necessary? I've tried a few Twitter videos (e.g. [this](https://twitter.com/BeatlemaniaUK/status/1075772555624046592)) and background playback worked fine for me.
Embedded Youtube videos (via an iframe) should work anyway and apart from that in practice the mobile Twitter page opens the full Youtube page anyway instead of playing the video in its embedded form.

**Comment by infohash** [comment]
@butterookie42 I've just tried it in firefox mobile. Background playback is working on twitter.

**Comment by buttercookie42** [comment]
Okay, in that case please re-open if Twitter ever changes its behaviour again.

**Comment by nils-werner** [comment]
Cannot reproduce, Twitter still stops/mutes playback when the tab is moved to the background...

**Comment by nils-werner** [comment]
Ah! If you **disable autoplay media**, videos will continue playing in the background.

**Pull request closed without merging**
